// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SpMV_SpMV,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3974,HLS_SYN_LUT=3864,HLS_VERSION=2024_1}" *)

module SpMV (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        values_address0,
        values_ce0,
        values_q0,
        columnIndexes_address0,
        columnIndexes_ce0,
        columnIndexes_q0,
        rowPointers_address0,
        rowPointers_ce0,
        rowPointers_q0,
        rowPointers_address1,
        rowPointers_ce1,
        rowPointers_q1,
        numOfRows,
        numOfCols,
        vector_address0,
        vector_ce0,
        vector_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 31'd1;
parameter    ap_ST_fsm_state2 = 31'd2;
parameter    ap_ST_fsm_state3 = 31'd4;
parameter    ap_ST_fsm_state4 = 31'd8;
parameter    ap_ST_fsm_state5 = 31'd16;
parameter    ap_ST_fsm_state6 = 31'd32;
parameter    ap_ST_fsm_state7 = 31'd64;
parameter    ap_ST_fsm_state8 = 31'd128;
parameter    ap_ST_fsm_state9 = 31'd256;
parameter    ap_ST_fsm_state10 = 31'd512;
parameter    ap_ST_fsm_state11 = 31'd1024;
parameter    ap_ST_fsm_state12 = 31'd2048;
parameter    ap_ST_fsm_state13 = 31'd4096;
parameter    ap_ST_fsm_state14 = 31'd8192;
parameter    ap_ST_fsm_state15 = 31'd16384;
parameter    ap_ST_fsm_state16 = 31'd32768;
parameter    ap_ST_fsm_state17 = 31'd65536;
parameter    ap_ST_fsm_state18 = 31'd131072;
parameter    ap_ST_fsm_state19 = 31'd262144;
parameter    ap_ST_fsm_state20 = 31'd524288;
parameter    ap_ST_fsm_state21 = 31'd1048576;
parameter    ap_ST_fsm_state22 = 31'd2097152;
parameter    ap_ST_fsm_state23 = 31'd4194304;
parameter    ap_ST_fsm_state24 = 31'd8388608;
parameter    ap_ST_fsm_state25 = 31'd16777216;
parameter    ap_ST_fsm_state26 = 31'd33554432;
parameter    ap_ST_fsm_state27 = 31'd67108864;
parameter    ap_ST_fsm_state28 = 31'd134217728;
parameter    ap_ST_fsm_state29 = 31'd268435456;
parameter    ap_ST_fsm_state30 = 31'd536870912;
parameter    ap_ST_fsm_state31 = 31'd1073741824;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] values_address0;
output   values_ce0;
input  [31:0] values_q0;
output  [6:0] columnIndexes_address0;
output   columnIndexes_ce0;
input  [4:0] columnIndexes_q0;
output  [3:0] rowPointers_address0;
output   rowPointers_ce0;
input  [8:0] rowPointers_q0;
output  [3:0] rowPointers_address1;
output   rowPointers_ce1;
input  [8:0] rowPointers_q1;
input  [4:0] numOfRows;
input  [4:0] numOfCols;
output  [3:0] vector_address0;
output   vector_ce0;
input  [31:0] vector_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] values_address0;
reg values_ce0;
reg[6:0] columnIndexes_address0;
reg columnIndexes_ce0;
reg[3:0] vector_address0;
reg vector_ce0;

(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] reg_710;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state29;
reg   [8:0] reg_724;
wire   [0:0] icmp_ln20_fu_738_p2;
reg   [0:0] icmp_ln20_reg_932;
wire   [0:0] icmp_ln20_1_fu_757_p2;
reg   [0:0] icmp_ln20_1_reg_946;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln20_2_fu_767_p2;
reg   [0:0] icmp_ln20_2_reg_960;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln20_3_fu_785_p2;
reg   [0:0] icmp_ln20_3_reg_974;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln20_4_fu_795_p2;
reg   [0:0] icmp_ln20_4_reg_988;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln20_5_fu_804_p2;
reg   [0:0] icmp_ln20_5_reg_1002;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln20_6_fu_813_p2;
reg   [0:0] icmp_ln20_6_reg_1016;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln20_7_fu_831_p2;
reg   [0:0] icmp_ln20_7_reg_1030;
wire    ap_CS_fsm_state22;
wire   [0:0] icmp_ln20_8_fu_841_p2;
reg   [0:0] icmp_ln20_8_reg_1044;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln20_9_fu_850_p2;
reg   [0:0] icmp_ln20_9_reg_1058;
wire    ap_CS_fsm_state28;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal_fu_560_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal_fu_560_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal_fu_560_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal_fu_560_sum_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_sum_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_sum_3_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_sum_3_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_sum_6_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_sum_6_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_sum_9_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_sum_9_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_sum_12_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_sum_12_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_sum_15_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_sum_15_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_sum_18_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_sum_18_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_sum_21_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_sum_21_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_sum_24_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_sum_24_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_ce;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_done;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_idle;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_ready;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_values_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_values_ce0;
wire   [6:0] grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_columnIndexes_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_columnIndexes_ce0;
wire   [3:0] grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_vector_address0;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_vector_ce0;
wire   [31:0] grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_sum_27_out;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_sum_27_out_ap_vld;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_din0;
wire  signed [31:0] grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_din1;
wire    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_ce;
reg   [31:0] ap_phi_mux_sum_1_phi_fu_444_p4;
reg   [31:0] sum_1_reg_440;
reg   [31:0] ap_phi_mux_sum_5_phi_fu_456_p4;
reg   [31:0] sum_5_reg_452;
reg   [31:0] ap_phi_mux_sum_8_phi_fu_468_p4;
reg   [31:0] sum_8_reg_464;
reg   [31:0] ap_phi_mux_sum_phi_fu_480_p4;
reg   [31:0] sum_reg_476;
reg   [31:0] ap_phi_mux_sum_9_phi_fu_492_p4;
reg   [31:0] sum_9_reg_488;
reg   [31:0] ap_phi_mux_sum_10_phi_fu_504_p4;
reg   [31:0] sum_10_reg_500;
reg   [31:0] ap_phi_mux_sum_11_phi_fu_516_p4;
reg   [31:0] sum_11_reg_512;
reg   [31:0] ap_phi_mux_sum_12_phi_fu_528_p4;
reg   [31:0] sum_12_reg_524;
reg   [31:0] ap_phi_mux_sum_13_phi_fu_540_p4;
reg   [31:0] sum_13_reg_536;
reg   [31:0] ap_phi_mux_sum_14_phi_fu_552_p4;
reg   [31:0] sum_14_reg_548;
wire    ap_CS_fsm_state31;
reg    grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start_reg;
wire    ap_CS_fsm_state21;
reg    grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start_reg;
wire    ap_CS_fsm_state24;
reg    grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start_reg;
wire    ap_CS_fsm_state27;
reg    grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start_reg;
wire    ap_CS_fsm_state30;
reg    rowPointers_ce1_local;
reg   [3:0] rowPointers_address1_local;
reg    rowPointers_ce0_local;
reg   [3:0] rowPointers_address0_local;
reg    output_r_we0_local;
reg   [31:0] output_r_d0_local;
reg    output_r_ce0_local;
reg   [3:0] output_r_address0_local;
wire   [3:0] tmp_fu_748_p4;
wire   [2:0] tmp_1_fu_776_p4;
wire   [1:0] tmp_2_fu_822_p4;
wire   [31:0] grp_fu_1072_p2;
reg  signed [31:0] grp_fu_1072_p0;
reg  signed [31:0] grp_fu_1072_p1;
reg    grp_fu_1072_ce;
reg   [30:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
#0 grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start_reg = 1'b0;
#0 grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start_reg = 1'b0;
end

SpMV_SpMV_Pipeline_spmv_loop_internal grp_SpMV_Pipeline_spmv_loop_internal_fu_560(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_ready),
    .zext_ln22(reg_710),
    .zext_ln22_1(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_vector_ce0),
    .vector_q0(vector_q0),
    .sum_out(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_sum_out),
    .sum_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_sum_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal1 grp_SpMV_Pipeline_spmv_loop_internal1_fu_575(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_ready),
    .zext_ln22_2(reg_710),
    .zext_ln22_3(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_vector_ce0),
    .vector_q0(vector_q0),
    .sum_3_out(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_sum_3_out),
    .sum_3_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_sum_3_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal2 grp_SpMV_Pipeline_spmv_loop_internal2_fu_590(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_ready),
    .zext_ln22_4(reg_710),
    .zext_ln22_5(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_vector_ce0),
    .vector_q0(vector_q0),
    .sum_6_out(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_sum_6_out),
    .sum_6_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_sum_6_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal3 grp_SpMV_Pipeline_spmv_loop_internal3_fu_605(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_ready),
    .zext_ln22_6(reg_710),
    .zext_ln22_7(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_vector_ce0),
    .vector_q0(vector_q0),
    .sum_9_out(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_sum_9_out),
    .sum_9_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_sum_9_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal4 grp_SpMV_Pipeline_spmv_loop_internal4_fu_620(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_ready),
    .zext_ln22_8(reg_710),
    .zext_ln22_9(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_vector_ce0),
    .vector_q0(vector_q0),
    .sum_12_out(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_sum_12_out),
    .sum_12_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_sum_12_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal5 grp_SpMV_Pipeline_spmv_loop_internal5_fu_635(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_ready),
    .zext_ln22_10(reg_710),
    .zext_ln22_11(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_vector_ce0),
    .vector_q0(vector_q0),
    .sum_15_out(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_sum_15_out),
    .sum_15_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_sum_15_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal6 grp_SpMV_Pipeline_spmv_loop_internal6_fu_650(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_ready),
    .zext_ln22_12(reg_710),
    .zext_ln22_13(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_vector_ce0),
    .vector_q0(vector_q0),
    .sum_18_out(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_sum_18_out),
    .sum_18_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_sum_18_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal7 grp_SpMV_Pipeline_spmv_loop_internal7_fu_665(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_ready),
    .zext_ln22_14(reg_710),
    .zext_ln22_15(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_vector_ce0),
    .vector_q0(vector_q0),
    .sum_21_out(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_sum_21_out),
    .sum_21_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_sum_21_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal8 grp_SpMV_Pipeline_spmv_loop_internal8_fu_680(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_ready),
    .zext_ln22_16(reg_710),
    .zext_ln22_17(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_vector_ce0),
    .vector_q0(vector_q0),
    .sum_24_out(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_sum_24_out),
    .sum_24_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_sum_24_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_ce)
);

SpMV_SpMV_Pipeline_spmv_loop_internal9 grp_SpMV_Pipeline_spmv_loop_internal9_fu_695(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start),
    .ap_done(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_done),
    .ap_idle(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_idle),
    .ap_ready(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_ready),
    .zext_ln22_18(reg_710),
    .zext_ln22_19(reg_724),
    .values_address0(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_values_address0),
    .values_ce0(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_values_ce0),
    .values_q0(values_q0),
    .columnIndexes_address0(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_columnIndexes_address0),
    .columnIndexes_ce0(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_columnIndexes_ce0),
    .columnIndexes_q0(columnIndexes_q0),
    .vector_address0(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_vector_address0),
    .vector_ce0(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_vector_ce0),
    .vector_q0(vector_q0),
    .sum_27_out(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_sum_27_out),
    .sum_27_out_ap_vld(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_sum_27_out_ap_vld),
    .grp_fu_1072_p_din0(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_din0),
    .grp_fu_1072_p_din1(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_din1),
    .grp_fu_1072_p_dout0(grp_fu_1072_p2),
    .grp_fu_1072_p_ce(grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_ce)
);

SpMV_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1072_p0),
    .din1(grp_fu_1072_p1),
    .ce(grp_fu_1072_ce),
    .dout(grp_fu_1072_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state26)) begin
            grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state29)) begin
            grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start_reg <= 1'b1;
        end else if ((grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_ready == 1'b1)) begin
            grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_5_fu_804_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        sum_10_reg_500 <= 32'd0;
    end else if (((icmp_ln20_5_reg_1002 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        sum_10_reg_500 <= grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_sum_15_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_6_fu_813_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        sum_11_reg_512 <= 32'd0;
    end else if (((icmp_ln20_6_reg_1016 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        sum_11_reg_512 <= grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_sum_18_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_7_fu_831_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        sum_12_reg_524 <= 32'd0;
    end else if (((icmp_ln20_7_reg_1030 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        sum_12_reg_524 <= grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_sum_21_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_8_fu_841_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        sum_13_reg_536 <= 32'd0;
    end else if (((icmp_ln20_8_reg_1044 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        sum_13_reg_536 <= grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_sum_24_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_9_fu_850_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        sum_14_reg_548 <= 32'd0;
    end else if (((icmp_ln20_9_reg_1058 == 1'd1) & (1'b1 == ap_CS_fsm_state31))) begin
        sum_14_reg_548 <= grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_sum_27_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln20_fu_738_p2 == 1'd1))) begin
        sum_1_reg_440 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln20_reg_932 == 1'd0))) begin
        sum_1_reg_440 <= grp_SpMV_Pipeline_spmv_loop_internal_fu_560_sum_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln20_1_fu_757_p2 == 1'd1))) begin
        sum_5_reg_452 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln20_1_reg_946 == 1'd0))) begin
        sum_5_reg_452 <= grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_sum_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln20_2_fu_767_p2 == 1'd0))) begin
        sum_8_reg_464 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln20_2_reg_960 == 1'd1))) begin
        sum_8_reg_464 <= grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_sum_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln20_4_fu_795_p2 == 1'd0))) begin
        sum_9_reg_488 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln20_4_reg_988 == 1'd1))) begin
        sum_9_reg_488 <= grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_sum_12_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln20_3_fu_785_p2 == 1'd1))) begin
        sum_reg_476 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln20_3_reg_974 == 1'd0))) begin
        sum_reg_476 <= grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_sum_9_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln20_1_reg_946 <= icmp_ln20_1_fu_757_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        icmp_ln20_2_reg_960 <= icmp_ln20_2_fu_767_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        icmp_ln20_3_reg_974 <= icmp_ln20_3_fu_785_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        icmp_ln20_4_reg_988 <= icmp_ln20_4_fu_795_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        icmp_ln20_5_reg_1002 <= icmp_ln20_5_fu_804_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        icmp_ln20_6_reg_1016 <= icmp_ln20_6_fu_813_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        icmp_ln20_7_reg_1030 <= icmp_ln20_7_fu_831_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        icmp_ln20_8_reg_1044 <= icmp_ln20_8_fu_841_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        icmp_ln20_9_reg_1058 <= icmp_ln20_9_fu_850_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln20_reg_932 <= icmp_ln20_fu_738_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_710 <= rowPointers_q1;
        reg_724 <= rowPointers_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_done == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_5_reg_1002 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        ap_phi_mux_sum_10_phi_fu_504_p4 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_sum_15_out;
    end else begin
        ap_phi_mux_sum_10_phi_fu_504_p4 = sum_10_reg_500;
    end
end

always @ (*) begin
    if (((icmp_ln20_6_reg_1016 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        ap_phi_mux_sum_11_phi_fu_516_p4 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_sum_18_out;
    end else begin
        ap_phi_mux_sum_11_phi_fu_516_p4 = sum_11_reg_512;
    end
end

always @ (*) begin
    if (((icmp_ln20_7_reg_1030 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        ap_phi_mux_sum_12_phi_fu_528_p4 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_sum_21_out;
    end else begin
        ap_phi_mux_sum_12_phi_fu_528_p4 = sum_12_reg_524;
    end
end

always @ (*) begin
    if (((icmp_ln20_8_reg_1044 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        ap_phi_mux_sum_13_phi_fu_540_p4 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_sum_24_out;
    end else begin
        ap_phi_mux_sum_13_phi_fu_540_p4 = sum_13_reg_536;
    end
end

always @ (*) begin
    if (((icmp_ln20_9_reg_1058 == 1'd1) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_phi_mux_sum_14_phi_fu_552_p4 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_sum_27_out;
    end else begin
        ap_phi_mux_sum_14_phi_fu_552_p4 = sum_14_reg_548;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln20_reg_932 == 1'd0))) begin
        ap_phi_mux_sum_1_phi_fu_444_p4 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_sum_out;
    end else begin
        ap_phi_mux_sum_1_phi_fu_444_p4 = sum_1_reg_440;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln20_1_reg_946 == 1'd0))) begin
        ap_phi_mux_sum_5_phi_fu_456_p4 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_sum_3_out;
    end else begin
        ap_phi_mux_sum_5_phi_fu_456_p4 = sum_5_reg_452;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln20_2_reg_960 == 1'd1))) begin
        ap_phi_mux_sum_8_phi_fu_468_p4 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_sum_6_out;
    end else begin
        ap_phi_mux_sum_8_phi_fu_468_p4 = sum_8_reg_464;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln20_4_reg_988 == 1'd1))) begin
        ap_phi_mux_sum_9_phi_fu_492_p4 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_sum_12_out;
    end else begin
        ap_phi_mux_sum_9_phi_fu_492_p4 = sum_9_reg_488;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln20_3_reg_974 == 1'd0))) begin
        ap_phi_mux_sum_phi_fu_480_p4 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_sum_9_out;
    end else begin
        ap_phi_mux_sum_phi_fu_480_p4 = sum_reg_476;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_columnIndexes_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        columnIndexes_address0 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_columnIndexes_address0;
    end else begin
        columnIndexes_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_columnIndexes_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        columnIndexes_ce0 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_columnIndexes_ce0;
    end else begin
        columnIndexes_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_1072_ce = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_ce;
    end else begin
        grp_fu_1072_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_1072_p0 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_din0;
    end else begin
        grp_fu_1072_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_grp_fu_1072_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_1072_p1 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_grp_fu_1072_p_din1;
    end else begin
        grp_fu_1072_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        output_r_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        output_r_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        output_r_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        output_r_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        output_r_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        output_r_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        output_r_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_r_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_address0_local = 64'd0;
    end else begin
        output_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        output_r_d0_local = ap_phi_mux_sum_14_phi_fu_552_p4;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        output_r_d0_local = ap_phi_mux_sum_13_phi_fu_540_p4;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        output_r_d0_local = ap_phi_mux_sum_12_phi_fu_528_p4;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        output_r_d0_local = ap_phi_mux_sum_11_phi_fu_516_p4;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        output_r_d0_local = ap_phi_mux_sum_10_phi_fu_504_p4;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        output_r_d0_local = ap_phi_mux_sum_9_phi_fu_492_p4;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        output_r_d0_local = ap_phi_mux_sum_phi_fu_480_p4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_r_d0_local = ap_phi_mux_sum_8_phi_fu_468_p4;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_d0_local = ap_phi_mux_sum_5_phi_fu_456_p4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_d0_local = ap_phi_mux_sum_1_phi_fu_444_p4;
    end else begin
        output_r_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        rowPointers_address0_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        rowPointers_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        rowPointers_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        rowPointers_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        rowPointers_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        rowPointers_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        rowPointers_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rowPointers_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rowPointers_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rowPointers_address0_local = 64'd1;
    end else begin
        rowPointers_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        rowPointers_address1_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        rowPointers_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        rowPointers_address1_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        rowPointers_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        rowPointers_address1_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        rowPointers_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        rowPointers_address1_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rowPointers_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rowPointers_address1_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rowPointers_address1_local = 64'd0;
    end else begin
        rowPointers_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        rowPointers_ce0_local = 1'b1;
    end else begin
        rowPointers_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        rowPointers_ce1_local = 1'b1;
    end else begin
        rowPointers_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        values_address0 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_values_address0;
    end else begin
        values_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        values_ce0 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_values_ce0;
    end else begin
        values_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_vector_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vector_address0 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_vector_address0;
    end else begin
        vector_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_vector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vector_ce0 = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_vector_ce0;
    end else begin
        vector_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln20_fu_738_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln20_fu_738_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln20_1_fu_757_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln20_2_fu_767_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln20_3_fu_785_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln20_4_fu_795_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln20_5_fu_804_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln20_6_fu_813_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((icmp_ln20_7_fu_831_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln20_8_fu_841_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            if (((icmp_ln20_9_fu_850_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start = grp_SpMV_Pipeline_spmv_loop_internal1_fu_575_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start = grp_SpMV_Pipeline_spmv_loop_internal2_fu_590_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start = grp_SpMV_Pipeline_spmv_loop_internal3_fu_605_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start = grp_SpMV_Pipeline_spmv_loop_internal4_fu_620_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start = grp_SpMV_Pipeline_spmv_loop_internal5_fu_635_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start = grp_SpMV_Pipeline_spmv_loop_internal6_fu_650_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start = grp_SpMV_Pipeline_spmv_loop_internal7_fu_665_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start = grp_SpMV_Pipeline_spmv_loop_internal8_fu_680_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start = grp_SpMV_Pipeline_spmv_loop_internal9_fu_695_ap_start_reg;

assign grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start = grp_SpMV_Pipeline_spmv_loop_internal_fu_560_ap_start_reg;

assign icmp_ln20_1_fu_757_p2 = ((tmp_fu_748_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln20_2_fu_767_p2 = ((numOfRows > 5'd2) ? 1'b1 : 1'b0);

assign icmp_ln20_3_fu_785_p2 = ((tmp_1_fu_776_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln20_4_fu_795_p2 = ((numOfRows > 5'd4) ? 1'b1 : 1'b0);

assign icmp_ln20_5_fu_804_p2 = ((numOfRows > 5'd5) ? 1'b1 : 1'b0);

assign icmp_ln20_6_fu_813_p2 = ((numOfRows > 5'd6) ? 1'b1 : 1'b0);

assign icmp_ln20_7_fu_831_p2 = ((tmp_2_fu_822_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln20_8_fu_841_p2 = ((numOfRows > 5'd8) ? 1'b1 : 1'b0);

assign icmp_ln20_9_fu_850_p2 = ((numOfRows > 5'd9) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_738_p2 = ((numOfRows == 5'd0) ? 1'b1 : 1'b0);

assign output_r_address0 = output_r_address0_local;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = output_r_d0_local;

assign output_r_we0 = output_r_we0_local;

assign rowPointers_address0 = rowPointers_address0_local;

assign rowPointers_address1 = rowPointers_address1_local;

assign rowPointers_ce0 = rowPointers_ce0_local;

assign rowPointers_ce1 = rowPointers_ce1_local;

assign tmp_1_fu_776_p4 = {{numOfRows[4:2]}};

assign tmp_2_fu_822_p4 = {{numOfRows[4:3]}};

assign tmp_fu_748_p4 = {{numOfRows[4:1]}};

endmodule //SpMV
