#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("values_address0", 7, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("values_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("values_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("columnIndexes_address0", 7, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("columnIndexes_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("columnIndexes_q0", 5, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("rowPointers_address0", 4, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("rowPointers_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("rowPointers_q0", 9, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("rowPointers_address1", 4, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("rowPointers_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("rowPointers_q1", 9, hls_in, 2, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("numOfRows", 5, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("numOfCols", 5, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("vector_address0", 4, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("vector_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("vector_q0", 32, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("output_r_address0", 4, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("output_r_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("output_r_we0", 1, hls_out, 6, "ap_memory", "mem_we", 1),
	Port_Property("output_r_d0", 32, hls_out, 6, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "SpMV";
